0xsoniclabs/sonic

Makefile, cmd/cmdtest/test_cmd.go, cmd/sonicd/app/launcher.go, cmd/sonictool/app/app_test.go, debug/flags.go, evmcore/tx_cacher.go, evmcore/tx_pool.go, gossip/handler.go
This PR is part of https://github.com/Fantom-foundation/sonic-admin/issues/90
It contributes by handling errors that do not need the caution util, nor occur in tests. These could have a real production impact, so they should be thoroughly tested much like https://github.com/Fantom-foundation/Sonic/pull/378
Norma test
- testing coverage https://docs.google.com/spreadsheets/d/1wma9IgKtWAePlPet0XdyoSQPRv5mU9tZspshbcd6jAc/edit?usp=sharing
this PR also enables `errcheck` as part of `make lint`
=> handle unhandled errors and enable errcheck

go.mod, go.sum
Part of https://github.com/0xsoniclabs/sonic-admin/issues/28
=> Update tosca version to use EIP-7702 updates.

eventcheck/epochcheck/epoch_check.go, evmcore/error.go, evmcore/tx_pool.go, evmcore/tx_pool_test.go
Transaction validation has been updated to cover checks for the Prague revision, including:
- Event checks for allowed transactions depending on revision.
- Tx Pool check for allowed transaction depending on revision and properties correctness. 
- Intrinsic gas check updated. (Only for TX pool, event check keeps the same validation until https://github.com/0xsoniclabs/sonic-admin/issues/90 updates it)
This PR does not include all the changes required for the transaction pool. It just implements basic validation of the transaction payload. A later PR shall include the changes regarding nonce and balance assumptions. 
This PR is part of https://github.com/0xsoniclabs/sonic-admin/issues/27
Todo:
=> Update Transaction validaton for Prague revision

utils/workers/workers.go, utils/workers/workers_test.go
This PR adds tests to the `workers` utils package and adds comments explaining how `workers` work.
Verification:
=> feat: workers tests

integration/makefakegenesis/genesis.go, integration/makefakegenesis/json.go, tests/eip2935_test.go
This PR adds the [EIP-2935](https://eips.ethereum.org/EIPS/eip-2935) pre-deployed contract to test infrastructure.
=> Add pre-deployed HistroyStorage Contract to fake nets started with Allegro

tests/rejected_tx_test.go
This PR introduces transaction type 4 in the rejected transactions integration test. 
Tests have been modified to cover:
- test all transaction types
- test both nonce and balance
This PR solves: https://github.com/0xsoniclabs/sonic-admin/issues/101
=> Refactor rejected transactions test

emitter/ancestor/fc_indexer.go, go.mod, go.sum, gossip/c_block_callbacks.go, gossip/emitter/piecefuncs.go, gossip/ethapi_backend.go
=> chore: update nomanclature observe => reach

emitter/ancestor/quorum_indexer.go, emitter/ancestor/sr_indexer.go, emitter/emission_sim_test.go, go.mod, go.sum, gossip/c_event_callbacks.go, gossip/emitter/config.go, gossip/emitter/emitter.go, gossip/emitter/hooks.go, gossip/emitter/parents.go, inter/drivertype/driver_type.go
=> chore: update nomenclature further

eventcheck/epochcheck/epoch_check.go, eventcheck/epochcheck/epoch_check_test.go, gossip/c_block_callbacks.go, gossip/c_block_callbacks_test.go, gossip/emitter/emitter.go, gossip/emitter/emitter_test.go, tests/single_proposer_protocol_test.go
This PR introduces support for a feature flag to control the enabling and disabling of the single-proposer protocol.
=> Integrate feature flag for single-proposer protocol

tests/integration_test_net.go, tests/single_proposer_protocol_test.go
Adds a set of quality-of-life functions to the `IntegrationTestNetSession` to simplify the implementation of tests including the handling of multiple accounts, in particular for stress-tests.
The added utilities include:
- an `EndowAccounts` function enabling the parallel endowment of multiple accounts; 
- a `RunAll` function sending in a list of transactions and waiting for their receipts
- a `GetChainId` function, eliminating the need to query the chain-ID through an RPC call
=> Add utility functions to run lists of transactions in parallel

tests/transaction_receipt_idx_test.go
Update to look for internal transactions.
=> Search for internal block-sealing transactions

README.md, cmd/sonictool/genesis/export.go, gossip/apply_genesis.go, gossip/evmstore/statedb_import.go, gossip/handler.go, gossip/service.go, opera/rules.go
This PR replaces outdated mentions of Fantom by Sonic.
=> Replace outdated Fantom mentions by Sonic

cmd/sonicd/app/launcher.go
While investigating how to reduce memory consumption it was also noticed that some goroutines were not properly closed. This PR adds a stope mechanism to `startNode` in `lachesisMainInternal`.
This PR is part of https://github.com/0xsoniclabs/sonic-admin/issues/244
=> Add stop mechanism to new nodes

gossip/filters/api.go
This PR adds weak pointer reference to `PublicFilterAPI`s timeout loop so that the API can be destroyed, the go routine of the timeout loop can also exit gracefully.
=> Add exit to timeout loop 

go.mod, go.sum
This PR updates the Tosca and Carmen dependencies to reference the latest versions.
=> Update Tosca and Carmen dependencies

scripts/license/add_license_header.go, scripts/license/add_license_header_test.go
We do not enforce our license on generated files.
=> license script ignores generated files

evmcore/tx_pool_test.go
This PR fixes a time sensitivity issue in a TxPool test. 
This PR fixes https://github.com/0xsoniclabs/sonic-admin/issues/260
The tests assumes that after each call to `addRemote` the reorder is executed. In this particular case of 2 transactions that kick out other transactions, the txpool needs to be reordered in between the two additions as well.
=> Fix TxPool drop underpriced flaky test

Dockerfile, Makefile
This PR updates the go lang version specified in the Dockerfile, as well as the docker file name and location in the makefile target.
=> Update Dockerfile and Makefile

README.md
Updates the README to list the correct Go version requirement.
=> Update Go version requirement in README

tests/log_subscription_test.go
this pr add the test. @jenikd  please rebase your branch first and it should be straight forward to merge
=> Add regression test against bloom issue

tests/block_override_test.go, tests/contracts/blockoverride/block_override.go, tests/contracts/blockoverride/block_override.sol
This PR is changing way how to instantiate a contract for a later interaction. The way how it was done before this PR might be possible source of test flakiness.
=> Simplify block override integration test

evmcore/state_processor_test.go
This PR extends unit tests for the state processor to increase the sensitivity regarding the indexing of receipts and log messages.
In particular, it re-confirms that the current state processor is indeed not ignoring skipped transactions when indexing logs and receipts. This should be further investigated. For now, this test shall ensure that this property is preserved during upcoming refactor steps.
=> Extend unit tests for state processor

evmcore/state_processor.go
This PR moves the transaction processing loop of the `StateProcessor`s `Process` function into a stand-alone function that can be re-used by the iterative `TransactionProcessor`.
=> Factor out transaction processing from StateProcessor

tests/gas_subsidies/test_utils.go
This PR adds a message to help during test development
=> Add message to sanity check

evmcore/tx_list.go, evmcore/tx_list_test.go, evmcore/tx_pool.go
This PR adds support for removing transactions that lost their sponsorship from the transaction pool.
=> Filter transactions with lost sponsorship in reorg
