0xsoniclabs/sonic

ethapi/api.go
ethapi/api_test.go
evmcore/error.go

This PR fixes situation, when gas estimation failed because of `intrinsic gas too low` error. Error was not correctly recognized, because raised error was from `go-ethereum` libary, not the one from `sonic` repository.

Fix recognition of intrinsic gas error

---

.github/CODEOWNERS

This PR removes the code-owner file since reviews from code owners are no longer enforced.
The general established development process on this and other sonic repositories does not include code owners. Instead contributors are required to select proper reviewers depending on the addressed feature. The definition of a static set of reviewers through an owner file is adding unnecessary noise (and sometimes delay) to the development process. Thus, this mechanism should be eliminated.

Remove code owners

---

cmd/sonicd/app/app.go
cmd/sonicd/app/launcher.go
cmd/sonicd/app/run_test.go
tests/integration_test_net.go

We experience flaky tests due to the selection of port numbers in integration tests that have already been used by other processes on the system. This change fixes this by allowing the OS to assign any free port number.
**Background**
When passing the port number 0 through the CLI to the `sonicd` client, an arbitrary free port is assigned to server sockets (for the P2P service and the web service). This code change is using this mechanism to avoid port collisions.
However, to inform the integration test infrastructure about the selected port, a back-channel needed to be added. Through this `sonicd` instances are able to inform the test infrastructure about the selected service port.
**Detail**
While working on this PR it was discovered that the HTTP and WebSocket traffic can be channeled …

Replace best-effort port probing with OS selected port numbers

---

debug/api.go
debug/trace.go

The CPU profiler and tracer failed to support stop calls in cases where they have not been started before. This caused the production of an error log message for sub-commands not starting them.
This PR fixes this by ignoring stop calls if the respective background service was not started before.
Fixes #16

Accept stop calls for profiler and tracer if never started

---

.github/workflows/release_build.yml
.github/workflows/test_build.yml

* GITHUB_TOKEN is not needed to do a release (when running in the same repo) (currently is release [failing](https://github.com/0xsoniclabs/sonic/actions/runs/13198761118/job/36845805842#step:7:18) because of invalid token)
* No private repositories are in dependencies anymore - removing ACCESS_TOKEN/GOPRIVATE
* Upgrade Go in workflow to 1.23
* Removed disabled unit tests (already set to run 0-times, because moved out from github)

Update Github Actions workflows

---

opera/legacy_serialization.go
opera/marshal_test.go
opera/rules.go

This PR introduces a hard fork flag to the network rules for the next sonic network hard fork.
The existing code base indicates hard forks through boolean flags in a struct. Although it would be cleaner to replace this flag-based representation by an enumeration type, such that invalid flag combinations are automatically excluded, such a change is difficult to realize in a backward compatible way. Thus, the new hard fork flag is added following the preexisting infrastructure.
Some existing tests got generalized to cover the unit-testing of the encoding and decoding of the new flag.

Add Allegro hard fork flag

---

ethapi/api.go
ethapi/transaction_args.go
gossip/gasprice/gasprice.go
utils/big.go
utils/big_test.go

In geth 1.15 the former `math.BigMin` and `math.BigMax` utility functions got removed by this [PR](https://github.com/ethereum/go-ethereum/commit/a5fe7353c) due to its name-space collision with the standard-libary `math` module. The suggested replacement is to inline the min/max decision.
However, this results in weakened readability, as seen in #24. By inlining the code, the intention of computing the maximum or minimum of two integers is harder to derive. Also, mixing up the argument order or a `< 0` for a `> 0` for the result of the `Cmp()` function is an easy mistake (as has happened to the author of #24). 
To counter that, this PR introduces generalized replacements for these functions in the `utils` module to retain readability.

Introduce BigMin / BigMax utils

---

ethapi/api.go
ethapi/api_test.go

This PR is related to https://github.com/Fantom-foundation/Sonic/issues/386 fixing issue, when transaction has to be simulated on empty block.

Replay transaction on empty block

---

go.mod
go.sum
scc/bls/bls.go
scc/bls/bls_test.go

This PR introduces a utility API for handling create and verify BLS signatures. The main involved components are:
- *PrivateKey*s and a secure key generation mechanism
- *PublicKey*s, which can be derived from private keys
- *Signatue*s, linking a document to a private key
- tools to aggregate public keys and signatures and to verify aggregated keys efficiently
Build on this, tools for the following tasks are provided:
- the serialization and deserialization of keys and signatures
- the validation of public keys and signatures
- the creation and verification of proof-of-possession signatures
Follow-up tasks for upcoming PRs:
- integrate test verifying the signature scheme against known key/msg/signature pairs
The BLST library is also used by the go-ethereum project (see …

Add implementation of a BLS library

---

scc/committee.go
scc/committee_test.go
scc/member.go
scc/member_test.go

This PR introduces data definitions for a Committee authorized to sign certificates.
A committee is composed of a group of members following these rules:
- there must be at least one member
- the public keys of all members must be unique
- all members must provide a proof-of-possession for their public keys
- all members must have a non-zero voting power
- the sum of the voting power must not exceed 2^64-1 (maximum of uint64)
In addition to the type definitions, debug printing and serialization support is added.

Add Member and Committee definitions

---

scc/cert/aggregated_signature_test.go
scc/cert/certificate_test.go
scc/cert/statement_test.go
scc/committee.go
scc/committee_test.go

This PR removes the implicit validity check of committees in the `NewCommittee` factory function.
This is motivated by multiple arguments:
- the factory can not grantee that all `Committee`s are valid; for instance, default instances are not valid, yet may be created by any external package; thus, any consumer of `Committee`s, for instance signature verification code, is required to explicitly validate committees either way
- the validity check in the constructor led to confusion in reviews by implying that all `Committee`s are always valid; this is not the case, as outlined above; thus, to avoid this issue, the implicit validity check was removed
- code using the `Committee` type may need finer control over the creation and validation of committees; for instance, when loading committees …

Remove implicit validity check in committee factory

---

opera/rules.go

This Pr adds the forktime for Prague to the chain config if the allegro update is enabled. 
Additionally, set fakenet to use the allegro update, used in integration tests and other testing. 
Required by https://github.com/0xsoniclabs/sonic-admin/issues/28

Update ChainConfig to enable Prague fork

---

.github/workflows/test_build.yml
go.mod
go.sum

By updating to this Go version we get support for the new features of [1.23](https://tip.golang.org/doc/go1.23) and [1.24](https://tip.golang.org/doc/go1.24), including:
- [iterator](https://tip.golang.org/doc/go1.23#language) support in for-range loops
- extensions to the [slices](https://pkg.go.dev/slices) library
- generic type aliases
- improvements in various tools like `vet` or `cgo`

Update Go version to 1.24

---

gossip/store.go
gossip/store_certificates.go
gossip/store_certificates_test.go

This PR introduces functionality to store and retrieve certificates in the client's central key/value store.

Introduce support for storing SCC certificates in the DB

---

gossip/store_certificates.go
gossip/store_certificates_test.go

This PR introduces support for iterating through certificates in their native order to the certification store.

Add support for iterating through certificates to DB

---

scc/bls/bls.go
scc/bls/bls_test.go
scc/cert/bitset_test.go
utils/jsonhex/types.go
utils/jsonhex/types_test.go

This PR:
- Fixes a formatting issue in jsonhex formatting issue.
- Adds a test in jsonhex that uses `json.Marshall` and `json.Unmarshall` to ensure this issues are caught.
- Adds json encoding functions for `bls.PublicKey` and `bls.Signature`.

add json encoding to public key and signature

---

cmd/sonictool/genesis/export.go
gossip/store_certificates.go
gossip/store_certificates_test.go
scc/cert/types.go
scc/node/store.go
scc/node/store_mock.go
scc/node/types.go

This PR introduces canonical definitions of the `CommitteCertificate` and `BlockCertificate` aliases in the `cert` package and replaces the former duplicated definitions in the `gossip` and `node` packages.

Create canonical certificate alias definitions

---

gossip/store_certificates.go
gossip/store_certificates_test.go

This PR extends the gossip DB interface to support fetching the latest committee and block certificates from the store. This is needed by the RPC service, as fetching for the `latest` certificate shall be supported.
Since the Ethereum DB interface does not support reverse-iteration through keys, a binary search is employed for finding the latest entries in the respective tables.

Add support for fetching the latest certificates

---

integration/assembly.go

When attempting to run node as validator after having ran once as RPC, an error has to be printed. 
The function here modified had a bug, overwriting pointers captured to do cleanups after the execution. 
This change removes the overwriting of named returns in the return statement.

Fix issue of error message not printed when running sonictool as validator with a rpc database. 

---

tests/contracts/batch/batch.go
tests/contracts/batch/batch.sol
tests/contracts/batch/gen.go
tests/contracts/privilege_deescalation/gen.go
tests/contracts/privilege_deescalation/privilege_deescalation.go
tests/contracts/privilege_deescalation/privilege_deescalation.sol
tests/set_code_tx_test.go
tests/transaction_gas_price_test.go

This PR depends on #56. Without it, it cannot be executed. 
This PR introduces a unit test for the [EIP-7702 transaction type](https://eips.ethereum.org/EIPS/eip-7702)
The proposed test has the following structure:
```
--- PASS: TestSetCodeTransaction (96.36s)
--- PASS: TestSetCodeTransaction/Operation (59.43s)
--- PASS: TestSetCodeTransaction/Operation/Delegate_can_be_set_and_unset (6.74s)
--- PASS: TestSetCodeTransaction/Operation/Invalid_authorizations_are_ignored (32.71s)
--- PASS: TestSetCodeTransaction/Operation/Invalid_authorizations_are_ignored/authorization_nonce_too_low (10.87s)
--- PASS: TestSetCodeTransaction/Operation/Invalid_authorizations_are_ignored/authorization_nonce_too_low/single_wrong_authorization (3.62s)
--- PASS: …
```

Add intergration test for type 4 transaction (set EOA code, eip-7702). 

---

utils/jsonhex/types.go
utils/jsonhex/types_test.go

Adds support for differentiating between `nil` and `[]byte{}` in the `jsonhex.Bytes` utility.

Fix encoding of nil and empty byte slices in JSON

---

scc/cert/bitset_test.go
utils/jsonhex/types.go
utils/jsonhex/types_test.go

This PR changes jsonhex.Byte encoding so that `nil` byte slices are encoded as the JSON null value instead of the string "null".

use json null instead of "null" in certificate encoding

---

cmd/sonictool/app/app_test.go
tests/address_access_test.go
tests/basefee_test.go
tests/blob_tx_test.go
tests/blobbasefee_test.go
tests/block_hash_test.go
tests/block_header_test.go
tests/block_override_test.go
tests/counter_test.go
tests/gas_price_suggestion_test.go
tests/genesis_import_test.go
tests/get_account_test.go
tests/initcoder_test.go
tests/integration_test_net.go
tests/integration_test_net_test.go
tests/invalid_start_test.go
tests/log_subscription_test.go
tests/node_restart_test.go
tests/prevrandao_test.go
tests/rejected_tx_test.go
tests/selfdestruct_test.go
tests/set_code_tx_test.go
tests/storage_override_test.go
tests/transaction_gas_price_test.go
tests/transaction_order_test.go
tests/transientstorage_test.go
tests/withdrawals_test.go

The issue when introducing parallel sub-tests using integration test networks is that cleanup would happen before sub-tests terminate, closing the network and crashing the tests. 
This change manages automatically cleanup registration in the context of t. 
- temp directory for client storage is generated from within the constructor.
- Net is automatically registered for cleanup in the context of t.
- Adding t as argument forces this code to be test only.

Change Integration test net constructors to improve test cleanup lifetimes. 

---

cmd/sonictool/app/app_test.go
tests/blob_tx_test.go
tests/gas_price_suggestion_test.go
tests/genesis_import_test.go
tests/initcoder_test.go
tests/integration_test_net.go
tests/integration_test_net_test.go
tests/invalid_start_test.go
tests/node_restart_test.go
tests/rejected_tx_test.go
tests/selfdestruct_test.go
tests/set_code_tx_test.go
tests/transaction_gas_price_test.go
tests/transaction_order_test.go
tests/withdrawals_test.go

This PR introduces a proxy account, which can be used to issue transactions in the same manner as the `IntegrationTestNet` object did before. 
Each subtest has a sequence of events, when such events use a disjoint set of accounts from the network, they can be executed concurrently with other workload. This PR introduces a `IntegrationTestNetSession` interface, with the already existing interface to execute transactions and retrieve information from a running network, but who's transactions are backed by a newly created account. 
The existing tests remain compatible, as the `IntegrationTestNet` already implements the interface.
- Set_code_tx_test reduces execution time from 180s to 50s.
- selfdestruct test reduces execution time from 40s to 25s. 
Two challenges arised during this …

Introduce integration test network sessions to parallelize integration test subtests.

---

ethapi/api.go
ethapi/api_test.go
tests/gossip_store_test.go
tests/transaction_store_test.go

This PR extends RPC transaction serialization to enable clients to query the transaction data after the transaction has included in the block. 
The PR introduces the changes in the serialization code, plus a json serialization test in the API code and an integration test for an End-to-end SetCode transactions lifetime in the client test.

Implement EIP-7702 support in rpc calls.

---

cmd/sonictool/app/app_test.go
integration/makefakegenesis/json.go
tests/block_header_test.go
tests/integration_test_net.go

This PR switches the genesis default for integration tests from a `fakenet` genesis to a test-package specific JSON genesis.
The `fakenet` genesis is a general feature facilitating the low-effort setup of a test net of multiple nodes for evaluation purposes. It is, for instance, used by Norma for setting up and running scenarios. Due to its scope, it is set up with a default event-emitter delay of 600ms, causing a block time of ~1 second.
For testing the JSON genesis feature, which is used for starting long-running networks like the Sonic main-net or public test nets, the integration test infrastructure also supports a mode to start a network using JSON file based genesis. This, so far, was only used for very few tests.
With this PR, the JSON genesis mode is made the default, and the …

Reduce block time in integration tests

---

cmd/sonicd/app/run_test.go
cmd/sonictool/app/app_test.go
cmd/sonictool/app/genesis.go
cmd/sonictool/app/main.go
gossip/common_test.go
gossip/emitter/emitter_test.go
gossip/gasprice/gasprice_test.go
integration/makefakegenesis/genesis.go
integration/makefakegenesis/json.go
opera/feature_set.go
opera/feature_set_test.go
opera/rules.go
tests/integration_test_net.go
tests/set_code_tx_test.go
tests/transaction_order_test.go
tests/transaction_store_test.go

This PR introduces the following changes:
- An argument to the fake net rules generation 
- A command line in the sonictool genesis fake command to specify the features profile.
- An "options" argument in the integration test net, which is optional and defaults to the previous status quo.

Introduce integration test net options to configure feature set enabled during testing. 

---

utils/datasemaphore/datasemaphore.go
utils/datasemaphore/datasemaphore_test.go

This PR adds tests to the `datasemaphore` utils package and adds comments explaining how `datasemaphore` works in detail - as it is a bit complicated.
The `Acquire` function has been rewritten because the previous implementation made it possible for `Acquire` to hang because the `sync.Cond` condition variable associated with the semaphore would never have `Broadcast()` called - while `Broadcast()` would potentially be triggered through the `Release` function called on the same semaphore instance - this is not guaranteed. A timer with a broadcast has now been added to the `Acquire` function and is called after the timeout to acquire the resources has elapsed to wake up **_all_** goroutines that may be waiting for a signal to retry - _including the same process that started the acquisition …

feat: datasemaphore tests

---

tests/state_test.go

Sonic's block processing and database supports all `Prague` features, the ethereum tests can be updated.

Update ethereum tests

---

cmd/sonicd/app/app.go
cmd/sonicd/app/launcher.go
cmd/sonicd/app/usage.go
cmd/sonictool/app/main.go
tests/integration_test_net.go
tests/integration_test_net_test.go

Adds support for running more than one node in Sonic's integration tests. This is required for integration tests targeting P2P layer features depending on the interactions of multiple nodes. In particular, upcoming tests for the certification chain are of this type.
To facilitate the clean operation of multiple nodes, the previous process-signaling based mechanism for triggering the shutdown of a node was replaced by an explicit control channel into the `sonicd` process. This allows to signal the request to shut down to individual nodes. Also, all usage of `os.Args` is eliminated. These changes eliminate further obstacles for running integration tests in parallel.

Add support for running multiple nodes in integration tests

---

ethapi/api.go
ethapi/api_test.go

This PR sets NoBaseFee parameter for vm config to true, to be able to replay transactions with gas price set to 0. This is usual for internal transactions.

Change NoBaseFee vm config parameter for replaying transaction

---

integration/makefakegenesis/json.go
scc/committee.go
scc/committee_test.go

The `GenesisJson` type stores the genesis committee as a `*scc.Committee`, which contains a private field. As a result, when encoding with `json.Marshal`, reflection couldn't access the committee members, causing them to be lost when exporting the genesis to a JSON file.
This PR introduces two key changes to address this issue:
- Adds two extra validation checks when decoding a JSON genesis: ensuring that the genesis committee has members and that they form a valid committee.
- Implements `MarshalJSON` and `UnmarshalJSON` methods for `scc.Committee` to properly handle JSON serialization.

Add json encode/decode methods to `scc.Committee`

---

integration/makefakegenesis/json.go
integration/makefakegenesis/json_test.go
tests/integration_test_net.go

This PR applies a number of improvements and fixes to the JSON genesis file handling:
- the functionality of producing a JSON genesis file following fake-net rules is moved from the integration `tests` package to the `makefakegenesis` package to be co-located with other fake-genesis related code
- the fake-genesis JSON file generation process was updated to produce a customize-able number of validators, allowing voting power to be distributed among multiple nodes in an integration test environment
- the provisioning of a genesis committee for the SCC is made optional to re-establish backward compatibility with the Sonic main-net JSON genesis file

Improve JSON genesis file infrastructure

---

cmd/sonictool/app/main.go
debug/flags.go
tests/integration_test_net.go

This PR introduces some changes in the logging initialization of the Sonic project.
- Introduces logging arguments into the sonictool. Log format, log level, per module verbosity, etc.
- Introduces an environment variable `SONIC_VERBOSITY` to tune log verbosity of sonictool, sonicd, and integration tests without recompiling.  
- Defaults to silent logs when running integration tests.
Example of use: 
`SONIC_VERBOSITY=3 go test -timeout 10m -run ^TestTransactionStore_CanTransactionsBeRetrievedFromBlocksAfterRestart$ github.com/0xsoniclabs/sonic/tests -v -count 1
`
This PR has been written with the "single point of responsibility" principle in mind, therefore the feature has been implemented in the command line arguments instead of duplicating the feature in the integration test tooling. …

Refactor logs initialization.

---

tests/generate_test_data_test.go

This PR adds testing tooling to facilitate the construction of inputs for tests. 
The use case will be to generate transaction types for validation or evaluation of execution based on different parametrization. 
The reason why the function requires a constructor is to guarantee stateless behavior during iteration. An alternative would have been to provide an `initial value` "a la fold". Nevertheless, to avoid deep-copy, the constructor function was introduced. 
Iterators are used instead of callbacks or slices to facilitate integration in loops and improve debuging of the tests using this code.

Add generate test data iterator

---

scc/light_client/light_client_state/light_client_state.go
scc/light_client/light_client_state/light_client_state_sync_test.go
scc/light_client/light_client_state/light_client_state_test.go

This PR depends on #91 
This PR adds the Light Client State (`LCS`). This represents the current state of the Light Client (`LC`), that is, up to which period and committee is the `LC` synced to. 
Two tests files are added:
- One aiming for unit testing, checking errors are properly propagated, etc.
- Another that generates a history of block certificates with the corresponding committee certificates (rotating between 3 different members), and then attempts to sync from a genesis committee to the period of the latest block reported by the `Provider`.

Add Light Client State

---

tests/set_code_tx_test.go

[Set code](https://eips.ethereum.org/EIPS/eip-7702) transactions are introduced with the [prague update.](https://eips.ethereum.org/EIPS/eip-7600)

Add integration test to verify that SetCode transaction are rejected before Allegro hardfork.

---

evmcore/error.go
evmcore/tx_pool.go
tests/gas_cost_test.go
tests/initcoder_test.go

This PR introduces calldata cost changes https://eips.ethereum.org/EIPS/eip-7623.
The transaction pool validation is extended to reject transactions not having enough Gas according to new formulas.
The test is introduced to check calldata costs, and its interaction with the sonic 10% cost of the unused gas rule.
Additionally, Init code size limit check has been added to the transaction pool validation to reject transactions which would otherwise be accepted to be ignored in the processor.

Add feature changes and test for EIP-7623

---

ethapi/api.go
ethapi/api_test.go
ethapi/block_overrides.go
gossip/ethapi_backend.go

This PR fixes an issue, when error was returned instead of nil, when block was not found.
It is related to [this issue](https://github.com/0xsoniclabs/sonic-admin/issues/116) where problem is decribed

Fix rpc response when block not found

---

cmd/sonicd/app/launcher.go
config/config.go
config/flags/flags.go
tests/integration_test_net.go
tests/integration_test_net_test.go

This PR adds a mechanism to change the configuration of the integration test net nodes. This is required because some flags are not exposed via command line flags. 
The changes here presented compromises in the following:
- The configuration is saved from a constructed node, instead of saving the configuration loaded directly. This is done this way because the initialization of the node contains accesses to the command line arguments at several stages of initialization. Making quite difficult to identify when is the configuration complete. This code aims to reduce code changes in that section while introducing the new feature. 
- Not every configuration field can be modified using this mechanism. The configuration structure contains both, non-serializable objects, and explicitly ignored …

Integration tests: Allow use of custom configuration in test nodes.

---

tests/integration_test_net.go
tests/integration_test_net_test.go
tests/revision_forward_test.go

To ensure the revision is forward correctly to the interpreter an integration test is added. This checks that the access cost for the delegation designation address is taken into account if Prague is enabled.

Add test to check revision is forwarded correctly

---

scc/light_client/light_client.go
scc/light_client/retry.go
scc/light_client/retry_test.go

This PR introduces the `retryProvider` type, which implements the `provider` interface while also wrapping an existing `provider` and automatically retries failed certificate fetch attempts. It follows the Decorator Pattern, ensuring that retry logic is separate from core provider implementations.
Additionally, the `retries` and `timeout` parameters are added to `light_client.Config`.

Add Retry provider to handle request failures

---

tests/eip2935_test.go

The HistoyStorage contract needs to be stored in a fix address, as decribed in https://eips.ethereum.org/EIPS/eip-2935.
> The bytecode will be deployed à la [EIP-4788](https://eips.ethereum.org/EIPS/eip-4788).
This means the use of a pre replay-protection transaction introduced in https://eips.ethereum.org/EIPS/eip-155.
This requires manual configuration of the node, for the RPC to accept this kind of transaction. 
This PR concludes https://github.com/0xsoniclabs/sonic-admin/issues/124

Test deployment of eip-2935

---

go.mod
go.sum
scc/light_client/multiplexer.go
scc/light_client/multiplexer_test.go
scc/light_client/provider.go
scc/light_client/provider_mock.go
scc/light_client/retry.go
scc/light_client/retry_test.go
scc/light_client/server.go
scc/light_client/server_test.go

This PR adds the `getAccountProof` function  to the interface and the different provider implementations. To enable unit testing  of this method a mock witness proof was needed from the `carmen` package, hence the update for this dependency.
`GetAccountProof` method takes an account address and a block height and returns the witness proof for it, which can be used to validate relevant information regarding that account at that height of the chain.

Add `getAccountProof` to providers

---

scc/light_client/light_client.go
scc/light_client/light_client_test.go

This PR adds the method `GetBalance` to the `LightClient` enabling it to ask for the balance of a given account, verifying it with the known state root certificate. 
This PR:
- adds the method `getAccountProof` which given an account, returns the witness proof for it, using the corresponding provider method.
- adds the method `GetBalance` which given an address, returns it's balance or an error. uses `getAccoutProof` to get a proof for the state's current head and the given address (of an account), and then validate it using the state's root hash.

Add `GetBalance` to `LightClient`

---

evmcore/tx_pool.go
evmcore/tx_pool_test.go

This PR updates the transaction validation logic to ensure proper ordering of transactions with authorization.
The previous check rejected a transaction if all the following conditions match:
- The sender had a delegation or pending delegation.
- There was at least one queued or pending transaction from the same sender.
- None of those transactions had the same nonce as the incoming transaction.
This approach led to an issue where:
- If a transaction with a higher nonce than expected was accepted first, and later a transaction with the expected nonce arrived, the latter would be rejected.
- This happened due to the "at most one in-flight transaction" policy introduced in https://github.com/0xsoniclabs/sonic/pull/74.
- As a result, the first transaction (with the higher nonce) would be …

Reject gapped tx from delegated account

---

ethapi/api.go
ethapi/api_test.go
ethapi/backend.go
ethapi/mock_backend.go
ethapi/tx_trace.go
evmcore/state_processor.go
gossip/ethapi_backend.go

Issue https://github.com/0xsoniclabs/sonic-admin/issues/128 describes a list of RPC methods which can execute a transaction in the RPC.
All these methods are calling one of the following internal routines: 
- `DoCall`, executes one transaction in a read-only mode. It is used by `DoEstimateGas` which ends up being used in many rpc methods.
- `StateAtTransaction`, executes a subset of one block transactions and returns the intermediate state. Used in debug and tracing methods.
- trace: `replayBlock`, similar to the previous, executes a subset of transactions included in a block. Used by other trace methods.
- `AccessList`, this is a tracing tool that helps pre-filling the access list for a transaction. This function exists 1:1 in [geth](https://github.com/ethereum/go-ethereum/blob/a775e68421 …

Modify RPC callbacks to execute EIP-2935 History Storage Contract.

---

tests/gas_cost_test.go
tests/integration_test_net.go
tests/integration_test_tools_test.go
tests/transaction_store_test.go

This PR introduces new function to fill in common fields in the transactions used for testing.
The goal is to reduce boilerplate code needed to configure nonce, gas, and gas price. While preserving the capacity to define any other field. 
The design works around the Geth inner transaction types, use these structs to configure payloads.
The reason why `setTransactionDefaults` and `signTransaction` are two separate symbols is to allow users to modify transaction payload after defaults are set (e.g. nonce override) 
The name `setTransactionDefaults` is inspired by the RPC function `SetDefaults` which provides a similar functionality.
This PR enables refactor of https://github.com/0xsoniclabs/sonic-admin/issues/101
Later changes will merge this new tools with the already existing `txFactory` …

Integration tests: Add better tooling to construct valid transactions.

---

tests/state_test.go

With the release of  [ethereum/tests v17.0](https://github.com/ethereum/tests/releases/tag/v17.0) the out dated eip-2537 tests got removed, they no longer need to be skipped in the test runner. 
Solves [#109](https://github.com/0xsoniclabs/sonic-admin/issues/109).

Remove eip-2537 test skipping

---

tests/state_test.go

The ethereum tests are no longer updated for all new eips, therefore the execution spec tests should be generated and ran against sonic to test its block processing and database. This PR extends the ethereum tests runner to also run the execution spec tests when filled.

Add execution spec tests

---

gossip/dummy_tx_pool.go
gossip/protocol.go
gossip/service.go

This PR fixes a node-shutdown issue seen in some integration tests by reporting an access to some `nil` pointer, like this:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfeea5d]
goroutine 4868 [running]:
github.com/Fantom-foundation/lachesis-base/utils/wlru.(*Cache).Get(0x0, {0x1b15800, 0xc016d96850})
/home/herbert/go/pkg/mod/github.com/!fantom-foundation/lachesis-base-sonic@v0.0.0-20250212122819-abaef8bb9abb/utils/wlru/wlru.go:50 +0x1d
github.com/0xsoniclabs/sonic/gossip.(*Store).GetBlock(0xc000328dc8, 0x5)
/home/herbert/coding/soniclabs/sonic/gossip/store_block.go:60 +0x3f
github.com/0xsoniclabs/sonic/gossip.(*EvmStateReader).getBlock(0xc00536a3a8, {0x1e, 0x25, 0x88, 0xe, 0xc0, 0x3e, 0x9e, 0x26, …
```

Fix stopping of TxPool background worker during service shutdown

---

tests/rejected_tx_test.go

Add-on to #176 
This PR adds a retry mechanism to wait for the tx pool to evict executed transactions once the state is updated.
It additionally refactors the generation of set code transactions with authorizations to avoid authorizations clash in the test.

Refactor reject-transaction integration test to avoid flakiness

---

tests/blob_tx_test.go

This PR removes flaky tests from the `BlobTransaction` test that are covered as well by the `RejectedTx` test. 
See #176 for details on why these tests are flaky.

Remove flaky blob transaction re-submission test covered by other tests

---

gossip/c_block_callbacks.go
gossip/scrambler/tx_scrambler.go
gossip/scrambler/tx_scrambler_fuzz_test.go
gossip/scrambler/tx_scrambler_test.go

This PR adds a fuzzing test for the public interface of the scrambler.
The fuzzer generates lists of transactions to be scrambled, shuffled and scrambled again to test reproducibility of the sorting algorithm. 
This PR moves the scrambler into its own package, this is done because fuzzing requires all tests from the package to pass before it can start.  This change reduces gossip package size, and it can be done because the scrambler does not depend on any other member of gossip.

Add fuzzer for scrambler 

---

opera/rules.go

This PR fixes the time units used in the documentation of some network rules.

Fix documentation of time units in network rules

---

ethapi/api.go
tests/eth_call_test.go

This PR modifies `eth_call` RPC function when there is contract code in account state override largen then the maximum allowed code for `LFVM` interpreter. In this case it uses `GETH` interpreter to simulate `eth_call`.

Use GETH for eth_call simulation with large code in state override

---

inter/proposer_selection.go
inter/proposer_selection_test.go

This PR introduces the algorithm used to select validators allowed to propose blocks from a list of validators.
The selection algorithm is selecting validators proportionally to their stake. Thus, a valdiator A with twice the stake of validator B will get selected twice as often for being a proposer for turns.

Add algorithm to select proposer for each turn

---

.gitignore
Makefile

This PR adds a new target to our Makefile, `integration-cover-all`. 
This new target will:
- create a new folder (`./coverage/{current-date}`)
- run the integrations tests (`go test ./tests/`) and produce a coverage report on all packages in `github.com/0xsoniclabs/sonic/`.
- the raw report will be in `./coverage/{current-date}/cover.out` and a friendlier human readable html report will be in  `./coverage/{current-date}/coverage.html`
The folder where all reports will be generated is included in `.gitignore` as to prevent uploading them by mistake.

Add `make integration-cover-all` target

---

inter/event.go
inter/event_serializer.go
inter/event_serializer_test.go
inter/event_test.go

This PR integrates the new `Payload` type into a new version for the Lachesis `Event` type.
This modification adds support for proposals to be annotated to events, thereby enabling the forwarding of proposals through the network as well as retaining them in the event database.

Introduce new event version using protobuffer payload

---

opera/rules.go
opera/rules_test.go
tests/network_rules_update_test.go

This PR updates copy of `MinBaseFee` to be deep copied for `Allegro` update only.  This prevent situation when a network runs pre-Allegro updated, but already running old and new version of the client. 
To prevent network issues, this enables deep copy of this property only when Allegro is enabled, which is possible only when majority of nodes is updated as well.

base fee deep copy allegro

---

gossip/blockproc/drivermodule/driver_txs.go
integration/makefakegenesis/json_test.go
integration/makegenesis/genesis.go
opera/marshal.go
opera/marshal_test.go
opera/rules.go
opera/validate.go
opera/validate_test.go
tests/integration_test_net.go

This PR introduces a network rule verification infrastructure and adds support for validating rule changes on the network.
The rule verification code covers basic rule properties by constraining the domain of various rule parameters. The main goal of those constraints is to prevent an accidental network stall. These validation steps are to be considered a last line of defense to safe-guard the network lifelines. However, they are necessarily incomplete. Any change of network rules should be tested extensively before being applied on production networks.
To facilitate a safe roll-out, the validation step is ignored by default. Only a rule-update will enable this features. To prevent a network split, the validation features should only be updated once sufficient (ideally all) nodes on the …

network rule validation

---

opera/validate.go
opera/validate_test.go
tests/network_rules_update_test.go

This PR tests that constraints set for MaxEventGas are realistic. It tats that
* Gas to update network rules does not exceeds 1M defined as the lowest limit, with headroom of 10times
* Gas to update network rules does not exceeds default limit, i.e. this value can be updated
* default and the lowest limit does not contradict

Check validity of constraints for MaxEventGas

---

tests/integration_test_net.go
tests/integration_test_net_test.go
tests/network_rules_update_test.go

This PR enriches integration tests with methods `AdvanceEpoch`. 
This method allows for progressing epoch by the configured number of steps.

Extends integration test with advance-epoch function

---

gossip/evmstore/statedb.go
gossip/service.go
gossip/service_test.go

This PR fixes situation, when there is no archive database for checking current block height when sending subscribers block notification
Related to https://github.com/0xsoniclabs/sonic-admin/issues/175

Check NoArchiveError when sending block notifications

---

inter/block.go
inter/block_test.go

This PR adds synchronization to the cached hash of the internal block structure.
The included unit tests revealed issues consistent with the problems reported by https://github.com/0xsoniclabs/sonic-admin/issues/177. While the effect was not observed end-to-end, as its reconstruction would be very timing sensitive, this is a plausible cause for the effect reported in the issue.

Synchronize access to cached hash in Block

---

tests/contracts/sponsoring/gen.go
tests/contracts/sponsoring/sponsoring.go
tests/contracts/sponsoring/sponsoring.sol
tests/set_code_tx_test.go

Rewrite test of use case with a more accurate workflow.
-  An account A issues a transaction (funds transfer for simplicity)  to account B
- An account B pays gas fees for it.
These changes replace the previously misleading example.

EIP-7702: Rewrite transaction sponsoring example

---

inter/event.go
inter/event_mock.go
inter/event_serializer.go
inter/event_serializer_test.go

This PR adds a flag to the event header indicating whether an event is carrying a block proposal or not.
While this is adding one bit of extra payload requirements, this extension is in line with other bits indicating the presence of transactions or votes in the event format. The information of the presence of a proposal in the event header is also required by the block processor to identify events carrying proposals (see #232 for its integration).

Add HasProposal flag to event header

---

gossip/filters/filter.go
gossip/filters/filter_test.go
tests/contracts/indexed_logs/gen.go
tests/contracts/indexed_logs/indexed_logs.go
tests/contracts/indexed_logs/indexed_logs.sol
tests/indexed_logs_test.go

This PR adds sorting of indexed logs. Indexed logs are searched in parallel and because of that they were not sorted. Sorting is done by `block number` and then by `log index` as log index is unique for a block.
Refers to [issue 129](https://github.com/0xsoniclabs/sonic-admin/issues/129)

Sort indexed logs

---

opera/legacy_serialization.go
opera/marshal_test.go
opera/rules.go
opera/rules_test.go
opera/validate.go

This PR introduces a feature-flag for the Single-Proposer protocol.
This PR only establishes the flag. Its actual integration into the code to have the desired effect is left for a follow-up RP.

Introduce feature flag for single-proposer protocol

---

evmcore/error.go
evmcore/tx_pool.go
evmcore/tx_pool_test.go
evmcore/tx_validation.go
evmcore/tx_validation_fuzzer_test.go
evmcore/tx_validation_test.go
tests/blob_tx_test.go
tests/set_code_tx_test.go

This PR refactors the `validateTx` function by breaking it into smaller functions, each grouped according to the type of validation and its dependencies. The goal is to make the validation logic more modular and reusable across packages—even in scenarios where some context (e.g., state, network rules) might be unavailable or irrelevant.
Network validations are performed first, because it is important to report unsupported transaction type as soon as possible. 
After network, validations are ordered to prioritize performance: cheaper checks are performed first, while more costly operations (like state access or complex computations) are deferred until later, and only executed if necessary.
New Validation Functions
These are the four introduced functions, listed in the order they are …

Split `validateTx` in `TxPool` 

---

evmcore/state_processor.go
evmcore/state_processor_test.go

This PR fixes 2 findings of ineffective assigns found a by `ineffassign` linter to be added by https://github.com/0xsoniclabs/sonic/pull/250.
ineffective assign analysis: the flagged assignment is `err = nil` before `continue`. When `continue` is called 2 things can happen:
- the loop starts again, in line 96 where `msg, err := TxAsMessage` writes over the value of `err`
- the loop ends and the value of `err` is returned. Given that there is no other assignment of `err` between the ineffectual `nil` assignment and the `return`, it is safe to just return `nil` and remove the assignment.

Fix ineffective assign issue.

---

debug/trace.go
evmcore/tx_pool.go
gossip/store_decided_state.go
inter/block.go
opera/rules.go
tests/integration_test_net.go
txtrace/trace_logger.go
utils/bits/bits.go
utils/dbutil/threads/pool.go
utils/fast/buffer.go

This PR fixes findings by `staticcheck` rule ST1020.
This rule enforces that the documentation, if any, of an exported method must begin with the name of the method.
This rule will be activated with https://github.com/0xsoniclabs/sonic/pull/250

Fix documentation of exported functions

---

config/config.go

This PR fixes finding by `staticcheck` rule `ST1022`.
This rule enforces that the documentation, if any, of an exported variable or constant must begin with the name of the variable or constant.
This rule will be activated with https://github.com/0xsoniclabs/sonic/pull/250

Fix documentation of exported variables

---

cmd/sonictool/app/main.go

This PR adds the `After` hook to the CLI, as without it [pprof](https://github.com/google/pprof), when used as an argument with `sonictool`, does not flush the `.prof` files required for profiling to disk and they would instead be empty files.
---
Example usage of this would be something like:
- seeding sonictool:
```
make sonictool
[place sonic.g, event100 files into ../dbs (or any appropriate genesis file, events file and DBs directory of your choice)]
./build/sonictool --datadir=../dbs genesis ../dbs/sonic.g
```
- running `sonictool` with `pprof` to generate profile database:
```
rm -rf ../dbs/carmen/archive
./build/sonictool --pprof.cpuprofile ../dbs/cpuprofile.prof --datadir=../dbs events import --mode=validator ../dbs/event100
```
- convert to `profile.pb.gz`:
```
cp …
```

Add After hook for sonictool

---

tests/chainid_test.go

As discussed in [PR #221](https://github.com/0xsoniclabs/sonic/pull/221#discussion_r2095551234), Sonic should support processing, storing, and retrieving transactions with `chainID = 0`.
The `Homestead` signer (used before [EIP-155](https://eips.ethereum.org/EIPS/eip-155)) does not include a `chainID` field and can only sign `Legacy` transactions (which also lacked `chainID` prior to [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718)).
All signers and transaction types introduced after EIP-155 include an explicit `chainID`.
- **Rejection** of transactions signed with post-Homestead signers if the `chainID` does not match the configured chain.
- **Acceptance and processing** of legacy transactions signed with `Homestead` signer:
- Transactions are accepted.
- After processing, the …

Add integration test for wrong chain-ID and chain-ID 0

---

cmd/cmdtest/test_cmd.go
config/config.go
ethapi/api.go
evmcore/tx_journal.go
gossip/blockproc/verwatcher/version_watcher.go
gossip/emitter/emitter.go
gossip/emitter/sync.go
opera/validate.go
utils/errlock/errlock.go

This PR fixes findings by `staticcheck` rule `ST1005`. 
This rule says that error strings must not begin with Capitalized letters, nor end with punctuation or new lines.
This rule will be activated with #250

Fix incorrectly formatted error strings

---

cmd/sonictool/app/genesis.go
cmd/sonictool/app/main.go

This PR is for parity with the current client to be able to profile with `sonictool`. The PR adds the `After` hook to the CLI, as without it [pprof](https://github.com/google/pprof), when used as an argument with `sonictool`, does not flush the `.prof` files required for profiling to disk and they would instead be empty files.
---
Example usage of this would be something like:
- seeding sonictool:
```
make sonictool
[place sonic.g, event100 files into ../dbs (or any appropriate genesis file, events file and DBs directory of your choice)]
./build/sonictool --datadir=../dbs genesis ../dbs/sonic.g
```
- running `sonictool` with `pprof` to generate profile database:
```
rm -rf ../dbs/carmen/archive
./build/sonictool --pprof.cpuprofile ../dbs/cpuprofile.prof --datadir=../dbs events import …
```

feat: add CLI hooks for pprof

---

gossip/c_block_callbacks_test.go
utils/permute.go
utils/permute_test.go

This PR is factoring out a utility to generate permutations of a given list from the `c_block_callbacks_test.go` unit test file into a general utility to facilitate proper re-use.

Factor out permutation utility for testing

---

cmd/sonicd/app/misccmd.go
go.mod
go.sum

This PR fixes findings by `staticcheck` rule `SA1019`.
This rule reports all the uses of dependencies that whose documentations says they are deprecated. For this two actions are taken:
- Update Carmen
- Get GOROOT from environment variable instead of using `runtime.GOROOT()` as suggested in the documentation (https://pkg.go.dev/runtime#GOROOT)
This rule will be activated with https://github.com/0xsoniclabs/sonic/pull/250

Fix deprecated dependencies

---

tests/set_code_trace_test.go

This PR adds an integration test that verifies the correct generation of call traces between contracts for the 7702 set code transaction.

Add integration test for trace and debug of set code transaction

---

cmd/sonicd/app/app.go
config/config.go
config/flags/flags.go

This change fixes a race condition in the propagation of the transaction-pool-validation disabling flag.
Before this PR, a global constant defining the default value of this flag was updated multiple times while running integration tests. With this change, this race condition is eliminated.
This is part of an effort to re-establish support for running race-detection tests on our integration tests.

Fix race-condition on test flag for transaction pool validation switch

---

gossip/emitter/proposals.go
gossip/emitter/proposals_mock.go
gossip/emitter/proposals_test.go
gossip/emitter/scheduler/integration_test.go
gossip/emitter/scheduler/processor_mock.go
gossip/emitter/scheduler/scheduler.go
gossip/emitter/scheduler/scheduler_test.go

This PR extends the constraints considered by the transaction scheduler to cover one additional limit: the total size of the scheduled transactions in bytes.
With this change, an upper limit for the size of proposals can be effectively enforced. Higher-priority transactions being to large to fit into a proposal are skipped in favor of lower-priority transactions.

Add transaction size limit support to scheduler

---

.golangci.yml
Makefile
gossip/emitter/emitter_test.go
valkeystore/signer.go

This PR introduces golangci-lint which is a go linters runner. Linters which are enabled includes:
- errcheck
- govet
- ineffassign
- misspell
- staticcheck
- unused
The linters currently used in Sonic are errcheck, govet, staticcheck and deadcode. All except deadcode are supported by golangci-lint. The runner supports unused tool which serves as unused code detection which has similar features as deadcode.
`make  lint` now uses golangci.
This PR also fixes two issues that have been introduced since the breaking rules were fixed.

Add golangci config

---

tests/transaction_receipt_idx_test.go

This PR adds an integration test to ensure that internal transactions do not alter the transaction index inside of the receipt.
Simple value transfers are performed with a epoch change in the middle, all produced blocks are checked if the transaction index in the block aligns with the one inside the receipt.

Test: Internal transactions don't impact receipt index

---

Makefile

This PR changes the connector in `make coverage` target, so that if running the tests or creating the coverage report fail, then the whole command reports a failure. 
In `bash` the connector `&&` is used as a lazy eval, that will return on the first failure, while `;` will execute all commands, regardless of intermediate exit status, and report the last exit status.

Force coverage report to fail on failed tests

---

config/make_node.go

While running data-race tests on the integration tests it was discovered that the transaction pool is not properly stopped before shutting down the database in case of a failure.
The race condition indicated that the transaction pool kept running in the background while the DB containing the current chain state was shut down. This lead to a data race. With this fix, the transaction pool is shut down before the DB is closed in case the startup of a node fails.

Register Tx-Pool for cleanup during node creation in case of a failure

---

go.mod
go.sum

This PR updates the geth dependency from the former https://github.com/0xsoniclabs/go-ethereum/commit/a6b1c7063681b1182042d3b3a91fe5c8ac3010b5 to https://github.com/0xsoniclabs/go-ethereum/commit/1c3a8f11446cac145644f3f1bf4fdfafad3634cc introducing [two fixes](https://github.com/0xsoniclabs/go-ethereum/compare/a6b1c7..1c3a8f11446cac145644f3f1bf4fdfafad3634cc) for data race issues.

Update geth dependency to include data race fixes

---

evmcore/state_processor.go
evmcore/state_processor_test.go

This PR adds a missing transaction termination call to complete the internal transaction keeping track of block hashes.
This feature has been introduced as part of the Prague feature package and is not yet actively used on the network. Without the call to `EndTransaction`, effects of the hash-tracking transaction are visible to the subsequent transaction in the same block. For instance, accessed accounts or value slots would be considered warm. Also, if there is no subsequent transactions, clean-up steps would get skipped. In particular, empty accounts touched by the internal transaction would not get cleaned up as expected.

Fix termination of parent-hash update transaction

---

evmcore/tx_pool.go
evmcore/tx_pool_test.go

As mentioned in https://github.com/0xsoniclabs/sonic/pull/271#discussion_r2126929274, the function `setMinTip` is only used in the repricing tests, and those repricing tests only tests the correct functionality of `setMinTip`. 
This PR removes unused functions `setMinTip` and `RemotesBelowTip` (which is only used in `setMinTip`), and refactors the repricing tests into two new tests.
New tests have been introduced instead:
- `TestTransactionPool_RejectsUnderTippedTransactions`
- `TestTransactionPool_AcceptsUnderTippedLocals`
Which as their names state, check that acceptance of transactions respects the min tip of the transaction pool for non local transactions.

Refactor txpool reprice tests 

---

gossip/c_block_callbacks.go
tests/block_header_test.go
tests/block_parameters_test.go
tests/contracts/block_parameters/block_parameters.go
tests/contracts/block_parameters/block_parameters.sol
tests/contracts/block_parameters/gen.go

While checking the alignment of block parameters between the scheduler and the block processor a difference in the used block time was discovered. The block processor was not using the time included in the proposal.
Before this PR, the time to be seen within transaction executions was set up [here](https://github.com/0xsoniclabs/sonic/blob/2221dd4be5e60f83cbd8f46b13f3c47bb86ef122/gossip/c_block_callbacks.go#L245-L246), by passing the [blockCtx](https://github.com/0xsoniclabs/sonic/blob/2221dd4be5e60f83cbd8f46b13f3c47bb86ef122/gossip/c_block_callbacks.go#L246) to the factory of the EVM-processor. This `blockCtx` contains the time of the atropos event, as it is set up [here](https://github.com/0xsoniclabs/sonic/blob/2221dd4be5e60f83cbd8f46b13f3c47bb86ef122/gossip/c_block_callbacks.go#L158), …

Fix handling of block time

---

eventcheck/proposalcheck/proposal_check.go
eventcheck/proposalcheck/proposal_check_test.go
gossip/emitter/proposals.go
gossip/emitter/proposals_test.go
inter/proposal_sync_state.go
inter/proposal_sync_state_test.go
inter/proposer_selection.go
inter/proposer_selection_test.go

This PR adds the epoch number to the seed for the verifiable random selection of proposers.
Before this change, the order of proposers in each block is equivalent as long as the stake distribution does not change. With this change, the epoch number adds additional randomness to the selection of proposers for individual turns.

Include epoch as seed in proposer selection

---

eventcheck/proposalcheck/proposal_check.go
eventcheck/proposalcheck/proposal_check_test.go

This PR adds an event validation step making sure that proposals may be attached only to version 3 events.
While serialization and deserialization of events right now are preventing proposals to be included in version 3 events, this check makes it a requirement in the event-validation as well -- which may be applied on an event instance that was derived from a different source than the deserialization of some data stream.
Preventing non-version 3 events from carrying proposals is also in line of the main objective of the event validation: to prevent spam in the event DAG.

Check that proposals are only included in version 3 events

---

ethapi/api.go
ethapi/api_test.go
evmcore/state_processor.go

This is main-branch variant of #307
Fixes debug_traceBlock for situation where tracing of a single tx fails:
**Before fix:**
```
curl 'http://localhost/' -X POST -H 'Content-Type: application/json' --data '{     
"jsonrpc": "2.0",
"method": "debug_traceBlockByNumber",
"params": [
"0x200873b",
{
"tracer": "callTracer",
"tracerConfig": {
"withLog": true
}
}
],
"id": 1
}' | jq
{
"jsonrpc": "2.0",
"id": 1,
"error": {
"code": -32000,
"message": "tracing failed: blob transaction missing blob hashes"
}
}
```

Fix error handling in debug_traceBlock - use error field

---

gossip/emitter/emitter.go
gossip/emitter/hooks.go
gossip/emitter/validators.go

The variables `Emitter.intervals.Min` and `Emitter.globalConfirmingInterval` are read during regular ticks, and assigned during new epoch creation. These read/write run in different threads (emitter tick and service routine) so these accesses need to be protected. 
This PR adds two mutexes for these two variables.

Protect concurrent emitter state access

---

tests/network_rules_update_test.go

This Change introduces one integration test, where an upgrade is rolled out and new features are accepted by the network. 
This pr depends on #276 and test should fail until merged.

Add integration test for HardFork Upgrade.

---

evmcore/state_processor.go
evmcore/state_processor_test.go
evmcore/tx_validation_fuzzer_test.go
gossip/blockproc/evmmodule/evm.go

The `log.Crit` call in the `Execute` function of the `OperaEVMProcessor` has been removed, by moving the error handling into the `Process` function of the `evmProcessor`. This allows to handle failing transactions separately and not on a block level. Failing transactions are ignored and the block processing continues with the next transaction.

Continue processing block after a failing transaction

---

eventcheck/proposalcheck/proposal_check_test.go
inter/proposal_sync_state_test.go
inter/turns.go

This PR reduces the timeout for determining failed proposal attempts to 3 frames.
Statistics from the Sonic network and practical evaluation using integration tests have demonstrated that the number of duplicated proposals is acceptable low at this level of sensitivity. Below 3 frames, competing proposals become frequent occurrences.
Up-coming full-scale tests of the system may provide additional insights in the effects of this parameters. If competing proposals are too frequent in those setups, it might have to be slightly raised again.

Reduce turn timeout to 3 frames

---

evmcore/state_processor.go
evmcore/state_processor_test.go
gossip/blockproc/evmmodule/evm.go
gossip/blockproc/evmmodule/evm_test.go
gossip/blockproc/interface.go
gossip/c_block_callbacks.go
gossip/emitter/proposals.go
gossip/emitter/proposals_test.go
gossip/emitter/scheduler/processor.go
integration/makegenesis/genesis.go
inter/gas_rate_control.go
inter/gas_rate_control_test.go

This RP introduces a check for the admissible gas limit for block proposals in the single-proposer mode.
**For Reviewers**
This PR applies three modifications:
- it moves the formerly private [`GetEffectiveGasLimit`](https://github.com/0xsoniclabs/sonic/blob/561abb92b658a7bc5cfe67a10af776528ca42ab4/gossip/emitter/proposals.go#L325) function from the `emitter` package into the `inter` package to make it available to the `gossip` package
- it extends the EVM State-Processor's [Process](https://github.com/0xsoniclabs/sonic/blob/561abb92b658a7bc5cfe67a10af776528ca42ab4/evmcore/state_processor.go#L72) function by an explicit gas-limit parameter for running the given transactions, independent of the overall block limit. While the block limit must be consistent for all transactions in a block, …

Add gas limit to single-proposer mode

---

eventcheck/basiccheck/basic_check.go
eventcheck/basiccheck/basic_check_test.go
eventcheck/basiccheck/intrinsic_gas_legacy.go
evmcore/error.go

The function `evmcore.IntrinsicGas` is only used in `eventcheck/basiccheck` and it is an outdated version of [geth's](https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L71). 
This PR moves `IntrinsicGas` from `evmcore` to the `basiccheck`, where the function will be kept for history reproduction, but this function should not be used anywhere else. Whenever needed the [geth's](https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L71) function should be used.

Move legacy intrinsic gas to basic check

---

tests/invalid_start_test.go
tests/selfdestruct_test.go

This PR implements a refactor in two integrations tests helper functions.
It shall pass `t` instead of `require.Assertion` in test functions.

Refactor in testing helper functions

---

gossip/emitter/single_proposer_protocol_test.go

This PR extends the existing liveness test for the single-proposer protocol by the option of faulty nodes.
After this PR, the following cases are covered:
- up to `N-1` silent validators, not making any proposals
- up to `N-1` faulty validators, making proposals for the wrong blocks
- up to `N-1` randomly silent or faulty validators
In each case, the test verifies that progress on the block chain can be retained as long as there is at least one honest participant.

Add faulty validators to liveness test of the single proposer protocol

---

tests/basefee_test.go
tests/blob_tx_test.go
tests/blobbasefee_test.go
tests/block_hash_test.go
tests/block_header_test.go
tests/block_in_archive_test.go
tests/chainid_test.go
tests/eip2935_test.go
tests/gas_cost_test.go
tests/gas_price_suggestion_test.go
tests/genesis_import_test.go
tests/initcoder_test.go
tests/integration_test_net_test.go
tests/integration_test_tools_test.go
tests/invalid_start_test.go
tests/log_subscription_test.go
tests/node_restart_test.go
tests/prevrandao_test.go
tests/rejected_tx_test.go
tests/revision_forward_test.go
tests/set_code_tx_test.go
tests/transaction_gas_price_test.go
tests/transaction_order_test.go
tests/transaction_store_test.go
tests/withdrawals_test.go

The `testings` package offers a `context()`, this should be used in all tests. 
This PR replaces the uses of `context.Background()` for the testing alternative. 
This PR depends on https://github.com/0xsoniclabs/sonic/pull/336

Use `t.Context` in integration tests

---

gossip/c_block_callbacks.go
gossip/emitter/proposals.go
gossip/emitter/proposals_test.go
inter/gas_rate_control.go
inter/gas_rate_control_test.go

This PR extends the computation of the effective gas limit for a block in the single proposer protocol by including consideration of the set block gas limit.

Consider block gas limit in effective gas limit computation

---

cmd/sonictool/app/genesis.go
cmd/sonictool/db/dbutils.go
cmd/sonictool/genesis/import.go

The command line flag `--statedb.cache` was not properly forwarded in the case of importing a json genesis file.
This PR fixes that issue by adding the cache size to `genesis.ImportParams` and `db.GossipDbParameters`

Apply cache size flag when importing genesis

---

gossip/handler.go

This change switches a node in validator node to consider it self synced as soon as it starts emitting events.
In the node's P2P setup, incoming transactions are ignored while the node is syncing up to the network ([here](https://github.com/0xsoniclabs/sonic/blob/e96b2eb27ded9a8632970371af54ac94e8e80630/gossip/handler.go#L756), [here](https://github.com/0xsoniclabs/sonic/blob/e96b2eb27ded9a8632970371af54ac94e8e80630/gossip/handler.go#L776), and [here](https://github.com/0xsoniclabs/sonic/blob/e96b2eb27ded9a8632970371af54ac94e8e80630/gossip/handler.go#L1151)). This is to avoid accumulating and propagating out-dated transactions. Once a node is reasonably synced, the node's status is updated to enable the handling of transactions ([here](https://github.com/0xsoniclabs/sonic/blob/e96b2eb27ded …

Consider node as synced once event emission starts

---

tests/integration_test_tools_test.go
tests/set_code_tx_test.go

Add a method to wait for transaction eviction from the pool. Use this method to solve the scenario where a new transaction conflicts with a recently executed one but not yet retired from the pool.

Fix flaky setcodetx integration test

---

cmd/sonicd/app/launcher.go

This PR adds a log warning if the `ftm` or `sonic` namespace is enabled for HTTP or WebSocket services.
Example report:
```
WARN [07-09|11:39:28.053] The 'ftm' API is deprecated, use 'eth' instead (--http.api).
WARN [07-09|11:39:28.053] The 'sonic' API is experimental and should not be used in production environments (--http.api).
WARN [07-09|11:39:28.053] The 'ftm' API is deprecated, use 'eth' instead (--ws.api).
```

Add warning on FTM and Sonic RPC namespaces

---

evmcore/tx_pool_test.go

A race condition was detected by our testing efforts. 
This PR fixes it by protecting an assignment with the locks of the corresponding struct.
This PR fixes https://github.com/0xsoniclabs/sonic-admin/issues/254

Protect concurrent assignment in txpool test

---

tests/chainid_test.go

In the efforts to reduce runtime of the integration tests, this PR uses the same integration test net instance for the two tests regarding chain ID and signer. 
It also makes the independent cases of invalid transactions parallel. 
This PR contributges to https://github.com/0xsoniclabs/sonic-admin/issues/258

Unify integration test net for chain id test

---

tests/integration_test_net_test.go
tests/integration_test_tools_test.go

This PR contributes to https://github.com/0xsoniclabs/sonic-admin/issues/258
In order to reduce the runtime of the integration tests, this PR reuses a single instance of the test net for various tests.
To avoid side effects or transaction nonce collitions, `EndowAccountsWithTokens`, `DeployContracts` and `InteractWithContract` tests take a `Session` instead of a network, so that they can Endow a new account without account or tx nonce colision, or overlap over deployed contracts.

Reuse net and parallel in test net tests

---

gossip/c_block_callbacks.go
gossip/c_block_callbacks_test.go

This PR adds testing for  `spillBlockEvents`
The function is responsible for scheduling events with a total gas consumption equal or smaller than the block gas limit. 
The test enforces the properties of the current implementation, changes to this algorithm may hurt history replayability. 
This PR includes the following changes: 
- Testing of function properties
- Refactor of function:
- write a canonical for loop instead of tailing break if
- remove `log.crit`. The reasoning behind is as follows:
An event considered for execution reaches the endBlock callback, this element is identified by hash and its payload needs to be recovered from the state. If no payload exists, this is a system corruption and there is no recovery possible.  `log.Crit` invocation ends program execution with a …

 Improve c_block_callbacks testing coverage: add test for spillBlockEvents  

---

tests/integration_test_net_test.go

This PR fixes a flaky test, removing a session spawning from inside a parallel section to outside of it.

FIX: fix flaky test in integration test net tests

---

tests/basefee_test.go
tests/counter_test.go
tests/session_dispenser.go

The previous recommended way to start a test net used to be calling `StartIntegrationTestNet` which is not only a verbose clear name, but it also catches the attention of someone looking at a test, making its importance very clear. 
With the introduction of `getSession` in [#397](https://github.com/0xsoniclabs/sonic/pull/397) this very important initialization step seems hidden by a smaller function name.
To recover this visual effect this PR renames `getSession` to `getIntegrationTestNetSession`.
This PR also removes a debug log that remained from development.

Rename getSession to getIntegrationTestNetSession

---

tests/integration_test_net.go
tests/large_transactions_test.go

This PR fixes https://github.com/0xsoniclabs/sonic-admin/issues/287, which describes a flaky test, due to the amount of parallelism in the test `testLargeTransactionLoadTest`, running it with `-race` took longer than anticipated and as a side effect the receipt for the transactions first submitted (last ones to be processed) got a long delay (between 1 and 6 minutes).
Now the tests is ignored when running with `-race`.

Ignore large transaction test when checking for race conditions

---

ethapi/transaction_args.go
ethapi/transaction_args_test.go

This PR adds support for Blob and SetCode txs in RPC routines using conversion to `*types.Transaction`. The most important one being `AccessList` computation.
Notice that the conversion may fail with ill-formed `transactionArgs`, and that the conversion function relies on setDefaults being called before. This behavior has not been changed to minimize code changes at this stage of the release cycle. 
Future changes in the RPC may remove the need for this function. 
contributes to https://github.com/0xsoniclabs/sonic-admin/issues/284

RPC API. Add Blob and SetCode transactions to transactionArgs to types.Transaction conversion.

---

tests/address_access_test.go
tests/blob_tx_test.go
tests/block_hash_test.go
tests/block_in_archive_test.go
tests/block_override_test.go
tests/bls_onchain_test.go
tests/create_skipped_test.go
tests/eth_call_test.go
tests/get_account_test.go
tests/prevrandao_test.go
tests/rejected_tx_test.go
tests/set_code_trace_test.go
tests/storage_override_test.go
tests/transaction_gas_price_test.go
tests/transientstorage_test.go
tests/withdrawals_test.go

This PR depends on https://github.com/0xsoniclabs/sonic/pull/421
Currently the integration tests take almost 30 minutes in CI, and as we implement new behaviour, more tests will need to be added and this is not sustainable for quick development cycle. 
The main focus of this PR is to replace calls to `StartIntegrationTestNet` with `getIntegrationTestNetSession`, reducing the number of test networks that need to be instantiated. 
Note This PR deals with the most straight forward cases. Other tests be migrated as well but need more changes. To keep the reviews as simple as possible, in this PR there is only replacement of function rename, but no logical chances.

Replace individual test networks with shared test networks

---

tests/set_code_tx_test.go

This PR implements two main changes in the set code transaction integration tests.
- Use a session from a shared network.
- Make all calls to `t.Parallel` after spawning new sessions to prevent same nonce flakyness.

Use sessions in set code integration test

---

tests/rpc_replay_test.go

Fixes: https://github.com/0xsoniclabs/sonic-admin/issues/219
With the refactor of https://github.com/0xsoniclabs/sonic/pull/276, ChainConfig is only valid for the duration of the block it was queried for. This PR adds testing for RPC entry points which behavior depends on computing the correct ChainCoinfig for the block height. Specially blocks near an upgrade.
The list of rpc entry points tested was manually selected, functions which use ChainConfig to deduce the right signer object are excluded: signer automatically selects a fitting signer for the transaction type, it cannot happen that they implement a different behavior for the same transaction depending on block height.

Add integration test for RPC calls at different block heights.

---

tests/network_rules_update/network_rules_update_test.go
tests/rpc_replay_test.go
tests/test_utils.go
tests/test_utils_test.go

This PR depends on https://github.com/0xsoniclabs/sonic/pull/430.
This PR moves to network rules update test into their own package so that the testing runtime can manage it in parallel to other packages.
This PR contributes to https://github.com/0xsoniclabs/sonic-admin/issues/258

Network rules update package

---

tests/pacing_of_empty_blocks/pacing_of_empty_blocks_test.go

This PR moves pacing of empty block test into their own package so that the testing runtime can manage it in parallel to other packages.
This PR contributes to https://github.com/0xsoniclabs/sonic-admin/issues/258

Pacing of empty block test package

---

tests/gas_cost/gas_cost_test.go

This PR depends on https://github.com/0xsoniclabs/sonic/pull/430.
This PR moves the gas cost test into their own package so that the testing runtime can manage it in parallel to other packages.
This PR contributes to https://github.com/0xsoniclabs/sonic-admin/issues/258

Gas cost package

---

config/config.go

Default arguments included deprecated API namespaces, which log a warning. 
This PR removes these from the default command line arguments.

Remove deprecated default command arguments

---

tests/integration_test_net_test.go

Tests with simulate multiple nodes, start multiple instances of the client, hence requiring more memory. The extra memory requirements plus the intense parallelism, excerpt the race detection analysis.
Serializing this tests reduces memory requirements by 3GBs, but increases runtime from ~30 seconds to ~1 minute. This is an acceptable trade off, considering that reducing memory requirements will improve stability of CI.

remove parallel from integration multi node tests

---

tests/integration_test_net.go
tests/rpc_replay_test.go
tests/test_utils_test.go

This PR removes two unnecessary epoch advancements from two tests, since calling `AdvanceEpochAndWaitForBlocks` already advances an epoch. It also moves the method `AdvanceEpoch` from `Session` to `IntegrationTestNet` as session should never attempt to advance epochs.

Move integration test advance epoch to the correct receiver

---

Makefile

Fuzzing of the sonic client has grown since the time when these targets were written.
Fuzzers now use Golang builtin fuzzing facilities and do not need installation of new tools (since https://github.com/0xsoniclabs/sonic/pull/441). 
The fuzzer tests at the time of this PR are:
```
func FuzzScrambler(f *testing.F) {
func FuzzScheduler_Schedule_PicksLongestPrefixOfAcceptedTransactions(f *testing.F) {
func FuzzGossipHandler(f *testing.F) {
func FuzzEventDeserialization(f *testing.F) {
func FuzzIsValidTurnProgression(f *testing.F) {
func FuzzPayloadDeserialization(f *testing.F) {
func FuzzValidateTransaction(f *testing.F) {
```
Since fuzzers are integrated into the CI scripts, this PR removes the need to maintain makefile targets for each of these. 
This PR and #441 fix …

Remove fuzzer targets from makefile

---

tests/test_utils.go
tests/test_utils_test.go

This PR fixes https://github.com/0xsoniclabs/sonic-admin/issues/340
This PR adds a wait for the transaction with nonce 1 to have left the pool, so that the new transaction will not be miss interpreted as a replacement.

Wait for processed transaction to leave tx pool

---

ethapi/api_test.go
go.mod
go.sum
gossip/evmstore/carmen.go
gossip/filters/filter_system_test.go
inter/state/adapter_mock.go

With the upcoming Fusaka update of ethereum, the geth dependency needs to upgraded. 
The integration has been run through the current ethereum execution spec test [release](https://github.com/ethereum/execution-spec-tests/releases/tag/fusaka-devnet-5%40v1.1.0) using the `TestState`.
After removing the `eip7939_count_leading_zeros` (not supported by lfvm yet), the following tests were failing:
- TestState/frontier/opcodes/all_opcodes/all_opcodes.json  (most likely due to missing clz opcode)
- TestState/osaka/eip7823_modexp_upper_bounds/modexp_upper_bounds/modexp_upper_bounds.json (two failing test cases)

Update geth dependency to 1.16.2

---

cmd/sonicd/app/unlocking_test.go

The following error was reported while attempting to test some other feature:
"    /Users/luis/code/sonic/cmd/sonicd/app/test_cmd.go:246: (stderr) failed to start the node: error starting protocol stack: listen Unix /var/folders/p9/b72p6b1n49x34qmdcgp8g1340000gn/T/TestUnlockFlagAmbiguousWrongPassword68034954/001/sonic.ipc:"
Although Mac supports unix-sockets, setup seems to be different. The tests edited are not dependent on unix-socket IPC and fixing it should be its own domain. With appropriate IPC testing.

Improve test support when using Apple OS

---

evmcore/tx_pool.go
evmcore/tx_pool_test.go
tests/network_rules_update/network_rules_update_test.go

This PR depends on https://github.com/0xsoniclabs/sonic/pull/472 and resolves https://github.com/0xsoniclabs/sonic-admin/issues/364
This PR adds two tests to verify that when `MaxEventGas` is updated, then all existing transactions with gas the over limit set by the rules should be discarded.
In the reference implementation this is done with a newly introduced purge before resets in [`runReorg`](https://github.com/ethereum/go-ethereum/blob/master/core/txpool/legacypool/legacypool.go#L1255). Geth needs to handle it this way because they have no other way of enforcing the new gas limit. 
Since in Sonic the new max gas cap (introduced with EIP7825) shall be instead set by a network parameter ([here](https://github.com/0xsoniclabs/sonic/blob/main/evmcore/tx_pool.go#L1422) in the TxPool, whose …

TxPool purges transactions with gas over rule limit

---

opera/legacy_serialization.go
opera/marshal_test.go
opera/rules.go
opera/rules_test.go
opera/validate.go
tests/gas_subsidiaries/gas_subsidiaries_test.go
tests/gassubsidies/gas_subsidies_test.go

This PR introduces a feature flag for the gas subsidies feature.
This PR only introduces the flag and an integration test verifying it can enabled/disabled for the 2 current feature sets.

Introduce feature flag for gas subsidies

---

evmcore/tx_pool.go
evmcore/tx_pool_test.go

This PR fixes  `checkDelegationLimit` function, to consider both `types.EmptyHash` as well as the zero value for `common.Hash` as empty codes.

Fix in code hash check.

---

gossip/blockproc/evmmodule/evm.go
gossip/blockproc/evmmodule/evm_test.go
gossip/blockproc/interface.go
gossip/blockproc/interface_mock.go
gossip/c_block_callbacks.go
gossip/c_block_callbacks_test.go
integration/makegenesis/genesis.go

This PR reduces the amount of information returned by the processor regarding skipped transactions to merely the number of skipped transactions.
Before this change, `EVMProcessor`s returned the list of indexes of issues transactions that got skipped. However, this information is effectively not used in the code. The two only uses are
- in the `c_block_callbacks.go` file, to report the number of skipped transactions
- in the `genesis.go` file, to list the indexes of the failed initialization issues in an error
Since with the upcoming introduction of transactions been introduced by the block processor the indexes of skipped transactions would even be harder to interpret correctly, this PR suggests to reduce the emitted information to merely the number of skipped transactions.
**Note:** as …

Update processor to only report number of skipped transaction

---

tests/invalid_start_test.go

This PR replaces the query for the Nonce for the query of the pending Nonce in the invalid start integration test.

Check pending nonce in invalid start integration test

---

evmcore/state_processor.go
evmcore/state_processor_test.go
gossip/blockproc/evmmodule/evm.go
gossip/blockproc/evmmodule/evm_test.go
gossip/blockproc/interface.go
gossip/blockproc/interface_mock.go
gossip/c_block_callbacks.go
gossip/c_block_callbacks_test.go

This PR updates the `StateProcessor` 's `Process` function to report the list of transactions it attempted to process. 
While in the current version this list is equivalent to the list of transactions being passed to it, upcoming changes will require the function to introduce additional transactions. The introduction of the ability to report the list of processed transactions facilitates this requirement.
The list of processed transactions are also reported by the `EVMProcessor`'s `Execute` function to allow those transactions to be accounted for in the block-formation covered by `c_block_callbacks.go`.

Make state processor report list of processed transactions

---

evmcore/tx_noncer.go
evmcore/tx_pool.go
evmcore/tx_pool_test.go
evmcore/tx_validation.go
gossip/evm_state_reader.go

This PR changes the source of state information from the pool from a scoped interface to the canonical sonic state.
This PR has two compromises:
- New interface has to manually be faked to avoid rewriting the large amount of testing inherited from Geth. 
- The pool has access to the full blockchain, and it is now capable of writing more intrusive and complex operations against the state. 
This PR facilitates later integration of the sponsored txs validation.

Refactor TxPool to use the sonic state interface

---

config/make_node.go
evmcore/subsidies_integration.go
evmcore/subsidies_integration_mock.go
evmcore/subsidies_integration_test.go
evmcore/tx_pool.go
evmcore/tx_pool_subsidies_test.go
evmcore/tx_pool_test.go
evmcore/tx_validation.go
evmcore/tx_validation_fuzzer_test.go
evmcore/tx_validation_test.go
gossip/handler_fuzz_test.go

The transaction pool validates sponsorship transactions requests. 
This PR and the previous one  #521 aim to reduce the amount of test code rewritten in tx_poo_tests.go. 
This is done by introducing a proxy object ( #521)  and segregating tests between two files:
- tx_pool_test.go logic remains untouched and can only test non-sponsored transactions
- tx_pool_subsidies_test.go contain tests which can enable the subsidies feature and use mocks for the state.
The logic of validating the subsidies is added to the tx_validate.go file.
To avoid boilerplate changes during review, the pr is separated in two commits.

Validate sponsored transactions when added to transaction pool

---

tests/gas_subsidies/test_utils.go
tests/gas_subsidies/test_utils_test.go

This PR depends on https://github.com/0xsoniclabs/sonic/pull/517
This PR adds a set of testing utilities to be used by the integration tests that will be added in the coming days. A test is added to show the expected usage of each utility.
Note that `validateSponsoredTxInBlock`  cannot be used until gas subsidies is fully implemented, so for now is not tested and there is a `//nolint` comment with it. This shall both be changed once the first integration test is merged.

Add gas subsidies test_utils functions

---

tests/gas_subsidies/log_order_test.go

This PR adds the missing review changes to the logs order test introduced in #536.

Gas subsidies log index integration test 

---

tests/gas_subsidies/all_tx_types_test.go

Updates the `TestGasSubsidies_SupportAllTxTypes` to reuse the same network for each transaction type.

Reuse chain for different transaction types

---

evmcore/state_processor_test.go

Removes two left-over TODOs in the `state_processor_test.go` file. 
These TODOs have been covered in the past:
- test progression of txIndex in sponsored transactions: [here](https://github.com/0xsoniclabs/sonic/blob/c5407a899a9518a578bbd3316368d36dbe4b9759/evmcore/state_processor_test.go#L1080-L1129) and [here](https://github.com/0xsoniclabs/sonic/blob/df228cd1943f8d939515ae9f934d3f62ce0294fc/tests/gas_subsidies/log_order_test.go#L97-L103)
- test that EVM is progressing txIndex by processed transactions: [here](https://github.com/0xsoniclabs/sonic/blob/df228cd1943f8d939515ae9f934d3f62ce0294fc/gossip/blockproc/evmmodule/evm_test.go#L193) and [here](https://github.com/0xsoniclabs/sonic/blob/df228cd1943f8d939515ae9f934d3f62ce0294fc/tests/gas_subsidies/log_order_test.go#L97-L103)

Remove remaining TODOs in state processor tests

---

tests/gas_subsidies/blockgas_test.go

This test checks that enough gas room to fit both the sponsored transaction and the internal transaction deducing funds.

Gas Subsidies: Add test for tx which does not fit in block
